### ISSUE TITLE
Clearer response message when command is disabled

### ISSUE THREAD

**Issue by derwild** [WFCD/genesis#113]
I had the case on my server, that the setting for creating private rooms was disabled, but I still tried to create on.
Because I didn't realize that there was even a global setting, I was confused to why the command would register (with reaction on my command from the bot) but nothing else happened, until @aliasfalse helped me understand it.

It think it would help the user experience, if the bot would tell the person issuing the command, that the setting is disabled globally.

If this is possible, it could also distinguish between a user, that is allowed to change the setting and one that is not.
It then either replies, that the setting is disabled and an 'admin' has to enable it (when the user doesn't have the permission) or gives the user the info on how to enable it.

**Comment by aliasfalse** [comment]
i'm looking into something wider with #115 that should help get this done as well

**Comment by aliasfalse** [comment]
I'm trying to figure out what you'd like to see beyond what's in, @derwild. I know it took me a while to re-review this heavily, but would you want it to respond to an attempt to make one that it's disabled? I guess I'm hesitant on this because it would mean sending lots of messages in places that it's purposely been told not to.

**Comment by TobiTenno** [comment]
welp, haven't been able to get more response...
