### ISSUE TITLE
[Suggestion] Update/append enemy alerts when enemy disappears

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [WFCD/genesis#225]
### Genesis Issue
---
**Summary (short):**
Currently, Genesis only sends messages when an enemy is discovered. While this is helpful, some enemies disappear after only a few minutes - knowing when this happens would be helpful.

---
**Description:**
Two possible methods for accomplishing this (assuming nothing is filtering out unknown-location enemies from the worldstate data) could be:
* Update the existing "Enemy found" messages when enemies disappear to change the side-band color to black and specify that said enemy has disappeared (sort of how the Giveaway bot in the WF Community Discord server works - see below)
* Send out a new message when the enemy disappears.
* Both of the above.

---
**Mockups, screenshots, evidence:**
Example of how GiveawayBot distinguishes between active/expired raffles:
![Example Screenshot](https://i.imgur.com/DoGHruX.png "Example of how GiveawayBot distinguishes between active/expired raffles")

---

(Check one)
- [ ] Issue
- [X] Suggestion

**Comment by TobiTenno** [comment]
> edit it
There are thousands sent out, we don't track where they are. Giveaway bot only has to edit one of these when such an event expires

> send another
Definitely possible, but we hadn't done so in the past due to it getting super spammy

If we did it, we'd most likely add another tracking type, like `enemies.depart` that would have to be individually tracked, cause i'm not causing the cetus tracking fiasco again

**Comment by TobiTenno** [comment]
Set up another trackable ✔️
